# Generated by Django 2.1.7 on 2019-04-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_companyprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
