# Generated by Django 2.1.7 on 2019-04-01 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_reviews_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='softwareproduct',
            name='reviews',
        ),
        migrations.AddField(
            model_name='reviews',
            name='software_product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='reviews.SoftwareProduct'),
            preserve_default=False,
        ),
    ]
