# Generated by Django 2.1.7 on 2019-04-02 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20190402_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='softwareproduct',
            old_name='description',
            new_name='product_description',
        ),
    ]
