# Generated by Django 2.1.7 on 2019-04-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_auto_20190403_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwareproduct',
            name='company_logo',
            field=models.ImageField(default='default.jpg', upload_to='media'),
        ),
    ]
