# Generated by Django 2.1.7 on 2019-04-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_auto_20190403_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwareproduct',
            name='website',
            field=models.URLField(default='http://google.com'),
            preserve_default=False,
        ),
    ]
