# Generated by Django 2.1.7 on 2019-04-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0015_remove_softwareproduct_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwareproduct',
            name='product_website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
