# Generated by Django 2.1.7 on 2019-04-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0017_softwareproduct_featured_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwareproduct',
            name='featured_product',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
    ]
