# Generated by Django 2.1.7 on 2019-04-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0018_auto_20190404_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwareproduct',
            name='product_website',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
