# Generated by Django 2.1.7 on 2019-04-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_auto_20190402_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwareproduct',
            name='company_logo',
            field=models.ImageField(upload_to=''),
        ),
    ]
