# Generated by Django 2.1.7 on 2019-04-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0016_softwareproduct_product_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwareproduct',
            name='featured_product',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='no', max_length=3),
            preserve_default=False,
        ),
    ]
