# Generated by Django 2.1.7 on 2019-04-04 14:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_auto_20190404_1302'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyProfile',
            new_name='Company',
        ),
    ]
